[build]
publish = "build/"
command = "npm run build"

[[redirects]]
from = "https://tjonesdev.netlify.app"
to = "https://www.tjonesdev.com"
status = 301
force = true

[[redirects]]
from = "/calculator_react/*"
to = "https://tjonesdev-calculator.netlify.app"
status = 200
force = true