[build]
publish = "build/"
command = "npm run build"

[[redirects]]
from = "https://tjonesdev.netlify.app"
to = "https://www.tjonesdev.com"
status = 301
force = true

[[redirects]]
from = "https://tjonesdev.github.io"
to = "https://www.tjonesdev.com"
status = 301
force = true

[[redirects]]
from = "/calculator_react/*"
to = "https://calculator.tjonesdev.com"
status = 301
force = true

[[redirects]]
from = "/pomodoro-clock_react/*"
to = "https://pomodoro.tjonesdev.com"
status = 301
force = true

[[redirects]]
from = "/drum-machine_react/*"
to = "https://drum.tjonesdev.com"
status = 301
force = true

[[redirects]]
from = "/markdown-previewer_react/*"
to = "https://markdown.tjonesdev.com"
status = 301
force = true

[[redirects]]
from = "/random-quote-machine_react_alt/*"
to = "https://quote.tjonesdev.com"
status = 301
force = true

[[redirects]]
from = "/technical-documentation-page_htmlcss/*"
to = "https://methods.tjonesdev.com"
status = 301
force = true

[[redirects]]
from = "/bookshelf_vanillajs/*"
to = "https://bookshelf.tjonesdev.com"
status = 301
force = true

[[redirects]]
from = "/slackers_v4_vanillajs_sass/*"
to = "https://slackers.tjonesdev.com"
status = 301
force = true
